In [1]:
import pandas as pd

In [2]:
cust_df = pd.read_excel('datasets/car_data.xlsx', sheet_name='Customer Data ')

In [3]:
cust_df

,Sr No,Customer name,CAR ID,Customer Purchase Model Name,PRICE,VARIANTS,Sales person Name,Date Of Vehicle Purchase,Total Accessories Sale,Unnamed: 9,Extended warranty purchase,Customer Voice,Customer Satsfied Remarks (1 to 10 number of rating)
0,1,Ramu Singh,C1,GLANZA,768815,E,Sanjay Kumar,2023-01-02,3500,NaN,Yes,Fully Satisfied,10
1,2,Anushka Tiwari,C11,INNOVA CRYSTA,2793490,2.4 VX 8 STR,Pramod Kumar,2023-01-04,2000,NaN,No,Partially Satisfied,6
2,3,Ramesh Singh,C11,INNOVA CRYSTA,2793490,2.4 VX 8 STR,Pramod Kumar,2023-01-05,0,NaN,No,Satisfied,8
3,4,DEVENDRA KUMAR,C11,INNOVA CRYSTA,2793490,2.4 VX 8 STR,Pramod Kumar,2023-01-07,1000,NaN,Yes,Satisfied,9
4,5,V.K Enterprises,C11,INNOVA CRYSTA,2793490,2.4 VX 8 STR,Pramod Kumar,2023-01-10,3000,NaN,Yes,Partially Satisfied,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,85,Pramod Kumar Verma,C24,HILUX,4341365,High AT,Jitendra Sharma,2023-12-02,1900,NaN,Yes,Satisfied,8
84,86,Shailendra Pratap Singh,C33,BALENO,905372,Delta AMT,Jitendra Sharma,2023-12-10,0,NaN,No,Satisfied,7
85,87,Ravi Kumar Sharma,C19,INNOVA HYCROSS,2931701,VX 7STR Hybrid,Jitendra Sharma,2023-12-17,2300,NaN,Yes,Partially Satisfied,4
86,88,Sangeet Vishwakarma,C24,HILUX,4341365,High AT,Jitendra Sharma,2023-12-20,3400,NaN,Yes,Fully Satisfied,10
87,89,AJEET AWASTHI,C34,BALENO,947771,ZETA,Jitendra Sharma,2023-12-25,2700,NaN,Yes,Partially Satisfied,4

In [4]:
import plotly.express as px

In [5]:
px.bar(cust_df, cust_df.index, 'Total Accessories Sale ', log_y=True)

In [6]:
liv_df= pd.read_excel('datasets/car_data.xlsx', sheet_name='Data ')
liv_df

,Vehicle Wholesale & Retail Tracking Data,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,NaN,NaN,NaN
1,Month,Wholesale Vehicle Model Name,Total Vehicle Wholesale,Total Vehicle Retail
2,2023-01-01 00:00:00,GLANZA,2,2
3,2023-01-01 00:00:00,INNOVA CRYSTA,4,4
4,2023-01-01 00:00:00,INNOVA HYCROSS,1,1
5,2023-02-01 00:00:00,DZIRE,3,3
6,2023-02-01 00:00:00,BALENO,2,2
7,2023-02-01 00:00:00,BREEZA,4,4
8,2023-02-01 00:00:00,ALTO K10,1,1
9,2023-02-01 00:00:00,CRETA,3,3
10,2023-03-01 00:00:00,GRAND I 10 NIOS,2,2
11,2023-03-01 00:00:00,AURA,3,3
12,2023-03-01 00:00:00,VERNA,1,1
13,2023-03-01 00:00:00,EXTER,3,3
14,2023-04-01 00:00:00,VENUE,4,4
15,2023-04-01 00:00:00,KONA ELECTRIC,3,3
16,2023-04-01 00:00:00,URBAN CRUISER HYRYDER,2,2
17,2023-05-01 00:00:00,FORTUNER LEGENDER,4,4
18,2023-05-01 00:00:00,HILUX,4,4
19,2023-06-01 00:00:00,INNOVA CRYSTA,3,3
20,2023-06-01 00:00:00,INNOVA HYCROSS,3,3
21,2023-07-01 00:00:00,VENUE,3,3
22,2023-07-01 00:00:00,EXTER,3,3
23,2023-08-01 00:00:00,ALTO K10,1,1
24,2023-08-01 00:00:00,INNOVA HYCROSS,1,1
25,2023-08-01 00:00:00,GRAND I 10 NIOS,2,2
26,2023-09-01 00:00:00,URBAN CRUISER HYRYDER,2,2
27,2023-09-01 00:00:00,HILUX,2,2
28,2023-10-01 00:00:00,ALTO K10,2,2
29,2023-10-01 00:00:00,ERTIGA,4,4
30,2023-11-01 00:00:00,INNOVA HYCROSS,3,3
31,2023-11-01 00:00:00,ALTO K10,4,4
32,2023-11-01 00:00:00,VERNA,2,2
33,2023-12-01 00:00:00,HILUX,3,3
34,2023-12-01 00:00:00,BALENO,2,2
35,2023-12-01 00:00:00,ERTIGA,1,1
36,2023-12-01 00:00:00,INNOVA HYCROSS,1,1

In [7]:
ct_df = pd.read_excel('datasets/car_data.xlsx', sheet_name='Car Details ')
ct_df

,Car Details,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr No,CAR ID,Brand Name,Model Name,Fuel Type,Engine Capacity - No. of cylinders OR FUEL TAN...,Varient,Ex Showroom Price,On road Price
2,1,C1,Toyotya,GLANZA,Petrol,4 Cylinders,E,681000,768815
3,2,C2,Toyotya,GLANZA,Petrol,4 Cylinders,S,770000,867075
4,3,C3,Toyotya,GLANZA,Petrol,4 Cylinders,G,873000,980792
5,4,C4,Toyotya,GLANZA,Petrol,4 Cylinders,V,973000,1091198
6,5,C5,Toyotya,URBAN CRUISER HYRYDER,Petrol,4 Cylinders,E,1073000,1233586
7,6,C6,Toyotya,URBAN CRUISER HYRYDER,Petrol,4 Cylinders,S CNG,1356000,1557769
8,7,C7,Toyotya,URBAN CRUISER HYRYDER,Petrol,4 Cylinders,S AT,1368000,1568269
9,8,C8,Toyotya,URBAN CRUISER HYRYDER,Petrol,4 Cylinders,G,1436000,1646186
10,9,C9,Toyotya,URBAN CRUISER HYRYDER,Petrol,4 Cylinders,HYBRID,1646000,1898694
11,10,C10,Toyotya,INNOVA CRYSTA,DIESEL,2.4L Diesel Engine- 4 CYLINDERS,2.4 VX 7 STR,2404000,2404000
12,11,C11,Toyotya,INNOVA CRYSTA,DIESEL,2.4L Diesel Engine- 4 CYLINDERS,2.4 VX 8 STR,2409000,2793490
13,12,C12,Toyotya,INNOVA CRYSTA,DIESEL,2.4L Diesel Engine- 4 CYLINDERS,2.4 ZX 7 STR,2568000,2975939
14,13,C13,Toyotya,INNOVA CRYSTA,DIESEL,2.4L Diesel Engine- 4 CYLINDERS,2.4 GX 7 STR,1999000,2323025
15,14,C14,Toyotya,INNOVA CRYSTA,DIESEL,2.4L Diesel Engine- 4 CYLINDERS,2.4 GX 8 STR,1999000,2323025
16,15,C15,Toyotya,INNOVA HYCROSS,PETROL,4 CYLINDERS,G 7STR,1882000,2186534
17,16,C16,Toyotya,INNOVA HYCROSS,PETROL,4 CYLINDERS,G 8STR,1887000,2193200
18,17,C17,Toyotya,INNOVA HYCROSS,PETROL,4 CYLINDERS,GX 7STR,1967000,2283635
19,18,C18,Toyotya,INNOVA HYCROSS,PETROL,4 CYLINDERS,GX 8STR,1972000,2290302
20,19,C19,Toyotya,INNOVA HYCROSS,PETROL,4 CYLINDERS,VX 7STR Hybrid,2530000,2931701
21,20,C20,Toyotya,FORTUNER LEGENDER,DIESEL,4 CYLINDERS,4x2 AT,4322000,4988610
22,21,C21,Toyotya,FORTUNER LEGENDER,DIESEL,4 CYLINDERS,4x4 AT,4694000,5415471
23,22,C22,Toyotya,HILUX,DIESEL,4 CYLINDERS,STD,3040000,3488783
24,23,C23,Toyotya,HILUX,DIESEL,4 CYLINDERS,High,3715000,4256107
25,24,C24,Toyotya,HILUX,DIESEL,4 CYLINDERS,High AT,3790000,4341365
26,25,C25,Toyotya,VELLFIRE,PETROL,4 CYLINDERS,Executive Lounge,9655000,11028270
27,26,C26,Toyotya,CAMRY,PETROL,4 CYLINDERS,2.5 Hybrid,4617000,5257689
28,27,C27,Maruti,DZIRE,PETROL,4 CYLINDERS,LXI,651500,739199
29,28,C28,Maruti,DZIRE,PETROL,4 CYLINDERS,VXI AT,799250,902651
30,29,C29,Maruti,DZIRE,PETROL,4 CYLINDERS,ZXI,812250,917033
31,30,C30,Maruti,DZIRE,PETROL,4 CYLINDERS,VXI CNG,839250,947714
32,31,C31,Maruti,BALENO,PETROL,4 CYLINDERS,Sigma,661000,750279
33,32,C32,Maruti,BALENO,PETROL,4 CYLINDERS,Delta,745000,844004
34,33,C33,Maruti,BALENO,PETROL,4 CYLINDERS,Delta AMT,800000,905372
35,34,C34,Maruti,BALENO,PETROL,4 CYLINDERS,Zeta,838000,947771
36,36,C35,Maruti,BREEZA,PETROL,4 CYLINDERS,Lxi,829000,941355
37,37,C36,Maruti,ALTO K10,PETROL,4 CYLINDERS,NaN,NaN,NaN
38,38,C37,Maruti,BREEZA,PETROL,4 CYLINDERS,Lxi CNG,924000,1048320
39,39,C38,Maruti,BREEZA,PETROL,4 CYLINDERS,Vxi,964500,1092198
40,40,C39,Maruti,ERTIGA,PETROL,4 CYLINDERS,Lxi (O),573400,662885
41,41,C40,Maruti,ERTIGA,PETROL,4 CYLINDERS,VXi (O),978000,1108946
42,42,C41,Maruti,ERTIGA,PETROL,4 CYLINDERS,Zxi (O),1088000,1264181
43,43,C42,Hyundai,GRAND I 10 NIOS,PETROL,4 CYLINDERS,Era,662900,763548
44,44,C43,Hyundai,GRAND I 10 NIOS,PETROL,4 CYLINDERS,Magna,718300,825859
45,45,C44,Hyundai,GRAND I 10 NIOS,PETROL,4 CYLINDERS,Sportz Executive,745900,851566
46,46,C45,Hyundai,I 20,PETROL,4 CYLINDERS,Magna,807600,920521
47,47,C46,Hyundai,I 20,PETROL,4 CYLINDERS,Sportz,822600,937285
48,48,C47,Hyundai,I 20,PETROL,4 CYLINDERS,Sportz DT,903500,1027697
49,49,C48,Hyundai,AURA,PETROL,4 CYLINDERS,E,632500,729357
50,50,C49,Hyundai,AURA,PETROL,4 CYLINDERS,S,717900,825410
51,51,C50,Hyundai,VERNA,PETROL,4 CYLINDERS,EX,1096500,1276286
52,52,C51,Hyundai,VERNA,PETROL,4 CYLINDERS,SX,1298500,1508098
53,53,C52,Hyundai,EXTER,PETROL,4 CYLINDERS,EX,599900,692690
54,54,C53,Hyundai,EXTER,PETROL,4 CYLINDERS,EX Opt,624990,720909
55,55,C54,Hyundai,VENUE,PETROL,4 CYLINDERS,N6 turbo DCT,1267300,1472294
56,56,C55,Hyundai,KONA ELECTRONICS,PETROL,4 CYLINDERS,PREMIUM,2384000,2503990
57,57,C56,Hyundai,CRETA,PETROL,4 CYLINDERS,EX,1181200,1366140
58,58,C57,Hyundai,CRETA,DIESEL,4 CYLINDERS,EX Diesel,1324000,1529756
59,59,C58,Maruti,ALTO K10,PETROL,4 CYLINDERS,STD,399000,456052

In [1]:
import pandas as pd
pd.set_option('display.max_columns',None)

In [2]:
df1 = pd.read_excel('datasets/car_data.xlsx',skiprows=2)
df2 = pd.read_excel('datasets/car_data.xlsx',sheet_name=2,skiprows=0)
df1.set_index('CAR ID', inplace=True)
df2.set_index('CAR ID', inplace=True)

In [4]:

df = df1.join(df2, how='left', rsuffix='_Customer')
df

,Sr No,Brand Name,Model Name,Fuel Type,Engine Capacity - No. of cylinders OR FUEL TANK CAPACITY,Varient,Ex Showroom Price,On road Price,Sr No _Customer,Customer name,Customer Purchase Model Name,VARIANTS,Sales person Name,Date Of Vehicle Purchase,Total Accessories Sale,PRICE,Extended warranty purchase,Customer Voice,Customer Satsfied Remarks (1 to 10 number of rating)
CAR ID,,,,,,,,,,,,,,,,,,,
C1,1,Toyotya,GLANZA,Petrol,4 Cylinders,E,681000.0,768815.0,1.0,Ramu Singh,GLANZA,E,Sanjay Kumar,2023-01-02,3500.0,768815.0,Yes,Fully Satisfied,10.0
C10,10,Toyotya,INNOVA CRYSTA,DIESEL,2.4L Diesel Engine- 4 CYLINDERS,2.4 VX 7 STR,2404000.0,2404000.0,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
C11,11,Toyotya,INNOVA CRYSTA,DIESEL,2.4L Diesel Engine- 4 CYLINDERS,2.4 VX 8 STR,2409000.0,2793490.0,2.0,Anushka Tiwari,INNOVA CRYSTA,2.4 VX 8 STR,Pramod Kumar,2023-01-04,2000.0,2793490.0,No,Partially Satisfied,6.0
C11,11,Toyotya,INNOVA CRYSTA,DIESEL,2.4L Diesel Engine- 4 CYLINDERS,2.4 VX 8 STR,2409000.0,2793490.0,3.0,Ramesh Singh,INNOVA CRYSTA,2.4 VX 8 STR,Pramod Kumar,2023-01-05,0.0,2793490.0,No,Satisfied,8.0
C11,11,Toyotya,INNOVA CRYSTA,DIESEL,2.4L Diesel Engine- 4 CYLINDERS,2.4 VX 8 STR,2409000.0,2793490.0,4.0,DEVENDRA KUMAR,INNOVA CRYSTA,2.4 VX 8 STR,Pramod Kumar,2023-01-07,1000.0,2793490.0,Yes,Satisfied,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C8,8,Toyotya,URBAN CRUISER HYRYDER,Petrol,4 Cylinders,G,1436000.0,1646186.0,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
C9,9,Toyotya,URBAN CRUISER HYRYDER,Petrol,4 Cylinders,HYBRID,1646000.0,1898694.0,31.0,SARASWATI MISHRA,URBAN CRUISER HYRYDER,HYBRID,Sanjay Kumar,2023-04-03,2000.0,1898694.0,Yes,Partially Satisfied,6.0
C9,9,Toyotya,URBAN CRUISER HYRYDER,Petrol,4 Cylinders,HYBRID,1646000.0,1898694.0,34.0,FEEROZ HAMID USMANI,URBAN CRUISER HYRYDER,HYBRID,Sanjay Kumar,2023-04-12,2900.0,1898694.0,No,Fully Satisfied,10.0
C9,9,Toyotya,URBAN CRUISER HYRYDER,Petrol,4 Cylinders,HYBRID,1646000.0,1898694.0,65.0,GARIMA SINGH,URBAN CRUISER HYRYDER,HYBRID,Shiv Tiwari,2023-09-03,2100.0,1898694.0,Yes,Partially Satisfied,5.0
C9,9,Toyotya,URBAN CRUISER HYRYDER,Petrol,4 Cylinders,HYBRID,1646000.0,1898694.0,68.0,LAXMI NARAYAN SINGH,URBAN CRUISER HYRYDER,HYBRID,Shiv Tiwari,2023-09-25,2100.0,1898694.0,No,Satisfied,8.0